const gramPerTeaspoon = [
  { id: 1, name: "醤油", grams: 6 },
  { id: 2, name: "味噌", grams: 6 },
  { id: 3, name: "みりん", grams: 6 },
  { id: 4, name: "酢", grams: 5 },
  { id: 5, name: "料理酒", grams: 5 },
  { id: 6, name: "塩", grams: 6 },
  { id: 7, name: "砂糖(上白糖)", grams: 3 },
  { id: 8, name: "グラニュー糖", grams: 4 },
  { id: 9, name: "小麦粉", grams: 3 },
  { id: 10, name: "片栗粉", grams: 3 },
  { id: 11, name: "薄力粉", grams: 3 },
  { id: 12, name: "強力粉", grams: 3 },
  { id: 13, name: "上新粉", grams: 3 },
  { id: 14, name: "米粉", grams: 3 },
  { id: 15, name: "パン粉", grams: 1 },
  { id: 16, name: "道明寺粉", grams: 4 },
  { id: 17, name: "サラダ油", grams: 4 },
  { id: 18, name: "ごま油", grams: 4 },
  { id: 19, name: "オリーブオイル", grams: 4 },
  { id: 20, name: "バター", grams: 4 },
  { id: 21, name: "牛乳", grams: 5 },
  { id: 22, name: "生クリーム", grams: 5 },
  { id: 23, name: "ラード", grams: 4 },
  { id: 24, name: "粉チーズ", grams: 2 },
  { id: 25, name: "ピザ用チーズ", grams: 3 },
  { id: 26, name: "マヨネーズ", grams: 4 },
  { id: 27, name: "ケチャップ", grams: 6 },
  { id: 28, name: "ウスターソース", grams: 6 },
  { id: 29, name: "オイスターソース", grams: 6 },
  { id: 30, name: "中濃ソース", grams: 6 },
  { id: 31, name: "コチュジャン", grams: 5 },
  { id: 32, name: "豆板醤", grams: 5 },
  { id: 33, name: "甜面醤", grams: 5 },
  { id: 34, name: "豆鼓醤", grams: 5 },
  { id: 35, name: "レモン汁", grams: 5 },
  { id: 36, name: "めんつゆ", grams: 6 },
  { id: 37, name: "ヨーグルト", grams: 5 },
  { id: 38, name: "鶏がらスープの素", grams: 2.5 },
];

export default gramPerTeaspoon;
